site_name: DBAX
site_url: http://dbax.io
site_description: Database Application eXpress
markdown_extensions: 
- admonition
- abbr
- nl2br
- smarty
- toc:
    permalink: True
- sane_lists
pages:
- Home: 'index.md'
- Bienvenido a DBAX: 'welcome.md'
- Introdcción:
  - 'Empezando': 'intro/empezando.md'
  - 'DBAX a simple vista': 'intro/a-simple-vista.md'
  - 'Funciones soportadas': 'intro/funciones-soportadas.md'
  - 'Diagrama de flujo': 'intro/diagrama-flujo.md'
- Tutoriales:
  - Tutorial:
      - 'Tutorial' : 'tutorial/index.md'
dev_addr: '0.0.0.0:8000'
theme: readthedocs